modularizacion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comentarios/', include('comentarios.urls')),
    path('post/', include('post.urls')),
    path('one/', include('onetoone.urls')),
    path('many/', include('manytoone.urls')),
    path('many2/', include('manytomany.urls')),
    path('company/', include('company.urls')),
]

post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.queris, name='prueba')
]

post/models.py
from django.db import models
from datetime import date

class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self) -> str:
        return f'{self.name.title()}'


class Entry(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    headline = models.CharField(max_length=255)
    body_text = models.TextField()
    public_date = models.DateField(default=date.today)
    rating = models.IntegerField(default=5)

    def __str__(self) -> str:
        return f'{self.headline}'

post/views.py
from django.shortcuts import render
from .models import Author, Entry

def queris(request):
    #obtener todos los objetos
    authors = Author.objects.all()

    # filtrado por el correo
    filtered = Author.objects.filter(email='zrose@example.org')

    #obteniendo el autor por el id
    author = Author.objects.get(id=1)

    #obtener los 10 primeros
    limits = Author.objects.all()[:10]

    #obtener los 5 elemento saltando los 5 primeros
    offsets = Author.objects.all()[5:10]

    #ordenar por email
    orders = Author.objects.all().order_by('email')

    # obtener y filtar por id colocando si es menor o igual 15
    # (__gte mayoy o igual)(__contains contiene)(__exat exacto)
    filtereds = Author.objects.filter(id__lte= 15)

    return render(
        request,
        'post/queris.html',
        {
            'authors': authors,
            'filtered':filtered,
            'author':author,
            'limits':limits,
            'offsets':offsets,
            'orders':orders,
            'filtereds':filtereds,
        }
    )

templates/post/queris.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
  <h3>Elemento mayor o igual a 15</h3>
  <ul>
    {% for operador in filtereds  %}
    <li> {{ operador.id}}  {{operador.email}} </li>
    {% endfor %}
  </ul>


  <h3>Elementos ordenados por orden</h3>
  <ul>
    {% for order in orders %}
    <li> {{order.email}} </li>
    {% endfor %}
  </ul>
  <h3>Total de elemntos: {{ orders|length }} </h3>

  <h3>Obtenindo los 5 despues de 10 de la lista</h3>
  <ul>
    {% for offset in offsets  %}
    <li> {{ offset.email }} </li>
    {% endfor %}
  </ul>

  <h3>Obtenindo los 10 primeros de la lista</h3>
  <ul>
    {% for limit in limits  %}
    <li> {{ limit.email }} </li>
    {% endfor %}
  </ul>

  <h3>Obteniendo el autor por la id() </h3>
  <p> {{ author }} </p>

  <h3>Buscando autor de emal = zrose@example.org</h3>
  <ul>
    {% for elm in filtered  %}
    <li>
      {{ elm.name }} | {{ elm.email }}
    </li>
    {% endfor %}
    <h3>Total de autores: {{ filtered|length }} </h3>
  </ul>
  <h3>Todos los autores</h3>
  <ul>
    {% for author in authors %}
    <li>
      {{ author.name }} ({{ author.email }})
    </li>
    {% for entry in author.entry_set.all %}
    <li>{{ entry }}</li>
    {% endfor %}
    {% endfor %}
  </ul>
  <h3>Total de autores: {{ authors|length }} </h3>
</body>
</html>